### ISSUE TITLE
AttributeError: _3D

### ISSUE THREAD

**Issue by komilaria** [yylgoodlucky/HDTR-Net#4]
how to solve issue

**Comment by komilaria** [comment]
is it work on windows?

**Comment by yylgoodlucky** [comment]
The code is tested on linux ubuntu 18.04. It seems like your problem is about your python environment. Since we don't have your running log, this issue could not be solve. Either paste your error log here or try it on linux.

**Comment by komilaria** [comment]
(hdtr-net1) PS C:\Users\USER\Desktop\aria\HDTR-Net> python inference.py --input_video sample/arialast.mp4
C:\Users\USER\miniconda3\envs\hdtr-net1\lib\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: 
  warn(f"Failed to load image Python extension: {e}")
Traceback (most recent call last):
  File "inference.py", line 20, in <module>
    fa_3d = face_alignment.FaceAlignment(face_alignment.LandmarksType._3D, flip_input=False, device='cuda:0')
  File "C:\Users\USER\miniconda3\envs\hdtr-net1\lib\enum.py", line 354, in __getattr__
    raise AttributeError(name) from None
AttributeError: _3D

**Comment by komilaria** [comment]
i am using Windows 11. maybe this issue depend on it?

**Comment by yylgoodlucky** [comment]
I think there may be an error in the version of face_alignment. You can refer to this answer [https://github.com/OpenTalker/video-retalking/issues/48](url)

**Comment by yylgoodlucky** [comment]
I think there may be an error in the version of face_alignment. You can refer to this 
[answer](https://github.com/OpenTalker/video-retalking/issues/48)

**Comment by alxsel** [comment]
You need to change _3D to THREE_D, and if you got same error but with _2D you need to change it to TWO_D.

**Comment by rebotnix** [comment]
Have the same issue on linux. Any idea?

-
raceback (most recent call last):
  File "inference.py", line 20, in <module>
    fa_3d = face_alignment.FaceAlignment(face_alignment.LandmarksType._3D, flip_input=False, device='cuda:0')
  File "/opt/8tbdrive1/experiments/HDTR-Net/venv/lib/python3.7/enum.py", line 349, in __getattr__
    raise AttributeError(name) from None
AttributeError: _3D

**Comment by kormalev** [comment]
A possible fix for this is to `pip install face-alignment==1.3.4` (or change it in requirements.txt).
