### ISSUE TITLE
KeyError: '00001.png'

### ISSUE THREAD

**Issue by komilaria** [yylgoodlucky/HDTR-Net#5]
Error loading the model:
PytorchStreamReader failed reading zip archive: failed finding central directory
Face alignment model could not be loaded. Please check the model files and dependencies.
[info] Step1: Prepare input data ...
==> detect face landmarks ...
  0%|                                                                                                                                                                   | 0/108 [00:00<?, ?it/s]Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
  3%|████▎                                                                                                                                                      | 3/108 [00:00<00:04, 22.97it/s]Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
  6%|████████▌                                                                                                                                                  | 6/108 [00:00<00:04, 24.52it/s]Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
  8%|████████████▉                                                                                                                                              | 9/108 [00:00<00:03, 25.07it/s]Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
 11%|█████████████████                                                                                                                                         | 12/108 [00:00<00:03, 25.31it/s]Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
 14%|█████████████████████▍                                                                                                                                    | 15/108 [00:00<00:03, 24.23it/s]Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
 17%|█████████████████████████▋                                                                                                                                | 18/108 [00:00<00:03, 24.73it/s]Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
 19%|█████████████████████████████▉                                                                                                                            | 21/108 [00:00<00:03, 25.01it/s]Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
 22%|██████████████████████████████████▏                                                                                                                       | 24/108 [00:00<00:03, 24.16it/s]Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
 25%|██████████████████████████████████████▌                                                                                                                   | 27/108 [00:01<00:03, 23.68it/s]Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
 28%|██████████████████████████████████████████▊                                                                                                               | 30/108 [00:01<00:03, 24.22it/s]Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
 31%|███████████████████████████████████████████████                                                                                                           | 33/108 [00:01<00:03, 24.64it/s]Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
 33%|███████████████████████████████████████████████████▎                                                                                                      | 36/108 [00:01<00:03, 23.96it/s]Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
 36%|███████████████████████████████████████████████████████▌                                                                                                  | 39/108 [00:01<00:02, 24.33it/s]Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
 39%|███████████████████████████████████████████████████████████▉                                                                                              | 42/108 [00:01<00:02, 23.87it/s]Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
 42%|████████████████████████████████████████████████████████████████▏                                                                                         | 45/108 [00:01<00:02, 24.39it/s]Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
 44%|████████████████████████████████████████████████████████████████████▍                                                                                     | 48/108 [00:01<00:02, 23.77it/s]Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
 47%|████████████████████████████████████████████████████████████████████████▋                                                                                 | 51/108 [00:02<00:02, 24.20it/s]Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
 50%|█████████████████████████████████████████████████████████████████████████████                                                                             | 54/108 [00:02<00:02, 24.68it/s]Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
 53%|█████████████████████████████████████████████████████████████████████████████████▎                                                                        | 57/108 [00:02<00:02, 25.09it/s]Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
 56%|█████████████████████████████████████████████████████████████████████████████████████▌                                                                    | 60/108 [00:02<00:01, 24.23it/s]Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
 58%|█████████████████████████████████████████████████████████████████████████████████████████▊                                                                | 63/108 [00:02<00:01, 24.67it/s]Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
 61%|██████████████████████████████████████████████████████████████████████████████████████████████                                                            | 66/108 [00:02<00:01, 24.80it/s]Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
 64%|██████████████████████████████████████████████████████████████████████████████████████████████████▍                                                       | 69/108 [00:02<00:01, 25.26it/s]Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
 67%|██████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                   | 72/108 [00:02<00:01, 25.38it/s]Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
 69%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                               | 75/108 [00:03<00:01, 25.49it/s]Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
 72%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                          | 78/108 [00:03<00:01, 24.50it/s]Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
 75%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                      | 81/108 [00:03<00:01, 24.67it/s]Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
 78%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                  | 84/108 [00:03<00:00, 25.20it/s]Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
 81%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                              | 87/108 [00:03<00:00, 25.32it/s]Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
 83%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                         | 90/108 [00:03<00:00, 25.46it/s]Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
 86%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                     | 93/108 [00:03<00:00, 24.59it/s]Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
 89%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                 | 96/108 [00:03<00:00, 24.54it/s]Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
 92%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏            | 99/108 [00:04<00:00, 24.34it/s]Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
 94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌        | 102/108 [00:04<00:00, 24.52it/s]Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
 97%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊    | 105/108 [00:04<00:00, 24.87it/s]Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
Catched the following error: 'NoneType' object has no attribute 'get_landmarks'
  0%|                                                                                                                                                                   | 0/108 [00:00<?, ?it/s] 
Traceback (most recent call last):
  File "c:/Users/USER/Desktop/aria/HDTR-Net/inference.py", line 246, in <module>
    frame_list = prepare_data(full_frame_path, result_path)
  File "c:/Users/USER/Desktop/aria/HDTR-Net/inference.py", line 178, in prepare_data
    landmark = read_landmarks[i]
KeyError: '00001.png'

**Comment by yylgoodlucky** [comment]
This error is actually located in `inference.py` **121 row**. Please check whether there are faces in your input video, and whether fa_3d has been instantiated successfully.  In addition, if you encounter an error, you can carefully check the log file.
